# Configurations
title:            Test Jekyll
longtitle:        Test Jekyll Multi-language Branches
author:           Author
email:            email@example.com
description:      Test Jekyll Multilanguage Branches languge separate branches like language/en

version:          1.0
gitbook_version:  3.2.3

url:              'https://jekyll.tamat.dev'
rss:              RSS

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

markdown_ext:     markdown,mkdown,mkdn,mkd,md

exclude:
  - _drafts

languages: ["ru", "en"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: ru
languageNames:
  ru: RU
  en: EN

collections:
  pages:
    output: true
    permalink: /:collection/:path/
    permalink_en: /en/:collection/:path/

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jemoji
  - jekyll-multiple-languages-plugin
